language: node_js
node_js: "8"
cache: yarn
script:
- "npm test"
- "npm run lint"
before_deploy:
- "npm run build"
deploy:
  provider: pages
  local_dir: "dist"
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
